import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import MaxWidthWrapper from './components/MaxWidthWrapper'
import StarsCanvas from './components/Three/StarsBackground'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Erik Buinevicius',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <StarsCanvas />
        <MaxWidthWrapper>{children}</MaxWidthWrapper>
      </body>
    </html>
  )
}
